spring:
  application:
    name: bank
  datasource:
    url: jdbc:postgresql://localhost:5432/final
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:databases/changelog-master.yml
  jpa:
    database: postgresql

ms:
  root:
    url: /v1/bank

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: mykey

